### ISSUE TITLE
Add dbt/include/sqlite/profile_template.yml

### ISSUE THREAD

**Issue by codeforkjeff** [codeforkjeff/dbt-sqlite#14]
Couldn't figure out how to do the schemas_and_paths and extensions parts

```yaml
fixed:
  type: sqlite
  threads: 1
  database: "database"
  schema: "main"
prompts:
  schemas_and_paths:
    main:
      hint: '/my_project/data/etl.db'
  schema_directory:
    hint: '/my_project/data'
  extensions:
    - "/path/to/sqlean/crypto.so"
```
