### ISSUE TITLE
dbt-sqlite generates profiles.yml with missing digest.so extension

### ISSUE THREAD

**Issue by dirkbosman** [codeforkjeff/dbt-sqlite#60]
### Issue Summary
After installing `dbt-sqlite` using `pip install dbt-core dbt-sqlite`, the generated `profiles.yml` file includes a reference to `sqlite-digest`, but this library no longer exists.
```
    ....
    prod:
      type: sqlite
      threads: 1
      database: <database name>
      schema: 'main'
      schemas_and_paths:
        main: '/my_project/data/etl.db'
      schema_directory: '/my_project/data'
      extensions:
        - '/path/to/sqlite-digest/digest.so'
    ....
```

### Steps to Reproduce
1. Install dbt for SQLite:
   ```sh
   pip install dbt-core dbt-sqlite
   ```
2. Run `dbt debug`
3. The error occurs:
   ```sh
   Runtime Error
   Database Error
   dlopen(/path/to/sqlite-digest/digest.so.dylib, 0x000A): tried: '/path/to/sqlite-digest/digest.so.dylib' (no such file)
   ```
4. Searching for digest.so confirms it does not exist:
   ```sh
   find /usr/local -name "digest.so" 2>/dev/null
   find /opt/homebrew -name "digest.so" 2>/dev/null
   ```

5. Also running `brew install sqlite-digest` if the following warning...   
   ```sh
   Warning: No available formula with the name "sqlite-digest". Did you mean sqlite-utils? Runtime Error.
   ```
This means the sqlite-digest extension (digest.so) is no longer available because the original GitHub repository (https://github.com/nalgeon/sqlite-digest) has been deleted. This means:
- dbt-sqlite mistakenly references a non-existent file
- There is no official way to install sqlite-digest right now other than a previous fork => https://github.com/mpdn/sqlite-digest

Suggested Fix:
- Remove the reference to digest.so from the default profiles.yml
- If digest.so is required, document how to install it properly.
